/** PostHog event names — keep stable for dashboards and funnels. */
export const AnalyticsEvents = {
  APP_OPENED: "app_opened",
  FIRST_CALL_STARTED: "first_call_started",
  FIRST_CALL_COMPLETED: "first_call_completed",
  PRACTICE_CAROUSEL_VIEWED: "practice_carousel_viewed",
  PRACTICE_TASK_OPENED: "practice_task_opened",
  PRACTICE_ATTEMPT_SUBMITTED: "practice_attempt_submitted",
  PRON_FEEDBACK_REQUESTED: "pron_feedback_requested",
  AZURE_PROSODY_STARTED: "azure_prosody_started",
  AZURE_PROSODY_COMPLETED: "azure_prosody_completed",
  AZURE_PROSODY_FAILED: "azure_prosody_failed",
  FEEDBACK_RENDERED: "feedback_rendered",
  FEEDBACK_HELPFUL_YES: "feedback_helpful_yes",
  FEEDBACK_HELPFUL_NO: "feedback_helpful_no",
  CALL_STARTED: "call_started",
  CALL_ENDED: "call_ended",
  AI_TUTOR_OPENED: "ai_tutor_opened",
  WORD_OF_DAY_PUSH_RECEIVED: "word_of_day_push_received",
  WORD_OF_DAY_PUSH_TAPPED: "word_of_day_push_tapped",
  PHRASE_OF_DAY_PUSH_RECEIVED: "phrase_of_day_push_received",
  PHRASE_OF_DAY_PUSH_TAPPED: "phrase_of_day_push_tapped",
  /** Emitted when word-of-day push is received on device */
  WORD_OF_DAY_PUSH_SENT: "word_of_day_push_sent",
  HOME_PRACTICE_CAROUSEL_VIEWED: "home_practice_carousel_viewed",
  HOME_PRACTICE_RECORD_STARTED: "home_practice_record_started",
  HOME_PRACTICE_RECORD_ENDED: "home_practice_record_ended",
  HOME_PRACTICE_ASSESS_COMPLETED: "home_practice_assess_completed",
  HOME_PRACTICE_DAILY_COMPLETED: "home_practice_daily_completed",
  HOME_PRACTICE_MISTAKE_STREAK_UPDATED: "home_practice_mistake_streak_updated",
  HOME_PRACTICE_LISTEN_TAPPED: "home_practice_listen_tapped",
  IN_CALL_HINT_SHOWN: "in_call_hint_shown",
  IN_CALL_HINT_USED: "in_call_hint_used",
} as const;

export type PracticeTaskType = "pronunciation" | "grammar" | "vocabulary" | string;
